/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainView;

import controller.MainViewController;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author Lab Informatika
 */
public class MainView extends javax.swing.JFrame {

    MainViewController mvc;
    private JTextField LabelStock;
    private JTable tabel;
    private JTextField LabelPemilihanKata;
    private JTextField LabelOriginalitas;

    /**
     * Creates new form MainView
     */
    public MainView() {
        this.mvc = new MainViewController(this);
        initComponents();
        mvc.isiTabel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Cari = new javax.swing.JTextField();
        CariJudul = new javax.swing.JToggleButton();
        CariAlur = new javax.swing.JToggleButton();
        CariOrisinalitas = new javax.swing.JToggleButton();
        CariPemilihanKata = new javax.swing.JToggleButton();
        BtnTambah = new javax.swing.JToggleButton();
        BtnUbah = new javax.swing.JToggleButton();
        BtnHapus = new javax.swing.JToggleButton();
        Cari1 = new javax.swing.JTextField();
        Cari2 = new javax.swing.JTextField();
        Cari3 = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CariJudul.setText("Judul");
        CariJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariJudulActionPerformed(evt);
            }
        });

        CariAlur.setText("Alur");
        CariAlur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariAlurActionPerformed(evt);
            }
        });

        CariOrisinalitas.setText("Orisinalitas");
        CariOrisinalitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariOrisinalitasActionPerformed(evt);
            }
        });

        CariPemilihanKata.setText("Pemilihan Kata");
        CariPemilihanKata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariPemilihanKataActionPerformed(evt);
            }
        });

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnUbah.setText("Ubah");
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        Cari3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cari3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Filosofi Kopi", "9.0", "9.5", "9.5", "9.33333333"},
                {"Hari Itu", "9.0", "9.0", "9.0", "9.0"},
                {"Kamis Sore", "7.5", "8.5", "8.5", "8.16666666666"},
                {"Minggu dengan Mu", "7.0", "5.0", "8.0", "6.666666666666"},
                {"Senja Kopi", "8.0", "8.0", "8.0", "8.0"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Judul", "Alur", "Orisinalitas", "Pemilihan Kata", "Nilai"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cari3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariJudul)
                    .addComponent(Cari1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariAlur)
                    .addComponent(Cari2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariOrisinalitas)
                    .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CariPemilihanKata)
                    .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BtnHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnUbah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(CariJudul)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Cari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CariAlur)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Cari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CariOrisinalitas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(CariPemilihanKata)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Cari3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnTambah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtnUbah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnHapus))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(326, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        mvc.insert();
        mvc.isiTabel();
        mvc.clear();
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        mvc.update();
        mvc.isiTabel();
        mvc.clear();
    }//GEN-LAST:event_BtnUbahActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        mvc.hapus();
        mvc.isiTabel();
        mvc.clear();
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void CariJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariJudulActionPerformed
        mvc.cariJudul();
    }//GEN-LAST:event_CariJudulActionPerformed

    private void CariAlurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariAlurActionPerformed
        mvc.cariGenre();
    }//GEN-LAST:event_CariAlurActionPerformed

    private void CariOrisinalitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariOrisinalitasActionPerformed
        mvc.cariPenulis();
    }//GEN-LAST:event_CariOrisinalitasActionPerformed

    private void CariPemilihanKataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariPemilihanKataActionPerformed
        mvc.cariPenerbit();
    }//GEN-LAST:event_CariPemilihanKataActionPerformed

    private void Cari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cari3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cari3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnHapus;
    private javax.swing.JToggleButton BtnTambah;
    private javax.swing.JToggleButton BtnUbah;
    private javax.swing.JTextField Cari;
    private javax.swing.JTextField Cari1;
    private javax.swing.JTextField Cari2;
    private javax.swing.JTextField Cari3;
    private javax.swing.JToggleButton CariAlur;
    private javax.swing.JToggleButton CariJudul;
    private javax.swing.JToggleButton CariOrisinalitas;
    private javax.swing.JToggleButton CariPemilihanKata;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public JToggleButton getBtnHapus() {
        return BtnHapus;
    }

    public void setBtnHapus(JToggleButton BtnHapus) {
        this.BtnHapus = BtnHapus;
    }

    public JToggleButton getBtnTambah() {
        return BtnTambah;
    }

    public void setBtnTambah(JToggleButton BtnTambah) {
        this.BtnTambah = BtnTambah;
    }

    public JToggleButton getBtnUbah() {
        return BtnUbah;
    }

    public void setBtnUbah(JToggleButton BtnUbah) {
        this.BtnUbah = BtnUbah;
    }

    public JTextField getCari() {
        return Cari;
    }

    public void setCari(JTextField Cari) {
        this.Cari = Cari;
    }

    public JToggleButton getCariGenre() {
        return CariAlur;
    }

    public void setCariGenre(JToggleButton CariGenre) {
        this.CariAlur = CariGenre;
    }

    public JToggleButton getCariJudul() {
        return CariJudul;
    }

    public void setCariJudul(JToggleButton CariJudul) {
        this.CariJudul = CariJudul;
    }

    public JToggleButton getCariPenerbit() {
        return CariPemilihanKata;
    }

    public void setCariPenerbit(JToggleButton CariPenerbit) {
        this.CariPemilihanKata = CariPenerbit;
    }

    public JToggleButton getCariPenulis() {
        return CariOrisinalitas;
    }

    public void setCariPenulis(JToggleButton CariPenulis) {
        this.CariOrisinalitas = CariPenulis;
    }

    public JTextField getLabelGenre() {
        return LabelGenre;
    }

    public void setLabelGenre(JTextField LabelGenre) {
        this.LabelGenre = LabelGenre;
    }

    public JTextField getLabelId() {
        return LabelId;
    }

    public void setLabelId(JTextField LabelId) {
        this.LabelId = LabelId;
    }

    public JTextField getLabelJudul() {
        return LabelJudul;
    }

    public void setLabelJudul(JTextField LabelJudul) {
        this.LabelJudul = LabelJudul;
    }

    public JTextField getLabelPemilihanKata() {
        JTextField LabelPemilihanKata = null;
        return LabelPemilihanKata;
    }

    public void setPemilihanKata(JTextField LabelPemilihanKata) {
        this.LabelPemilihanKata = LabelPemilihanKata;
    }

    public JTextField getLabelOriginalitas() {
        JTextField LabelOriginalitas = null;
        return LabelOriginalitas;
    }

    public void setLabelOriginalitas(JTextField LabelOriginalitas) {
        this.LabelOriginalitas = LabelOriginalitas;
    }

    public JTextField getLabelStock() {
        JTextField LabelStock = null;
        return LabelStock;
    }

    public void setLabelStock(JTextField LabelStock) {
        this.LabelStock = LabelStock;
    }

    public JTable getTabel() {
        JTable tabel = null;
        return tabel;
    }

    public void setTabel(JTable tabel) {
        this.tabel = tabel;
    }

    public JTextField getLabelPenerbit() {
        return LabelPenerbit;
    }

    public void setLabelPenerbit(JTextField LabelPenerbit) {
        this.LabelPenerbit = LabelPenerbit;
    }

    public Object getLabelAlur() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getLabelOrisinalitas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getLabelPemilihanKata() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getLabelNilai() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
